FaceRecogInterface/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recognition.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recognition/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings

app_name='recognition'

urlpatterns = [
 	path('', views.Home.as_view(), name='home'),
 	path('settings/', views.Home.as_view(), name='settings'),

 	path('login/', views.UserLoginView.as_view(), name='login'),
 	path('logout/', views.LogoutView.as_view(), name='logout'),
 	path('register/', views.UserRegistrationView.as_view(), name='register'),
 	path('settings/profile/', views.ProfileSettingsView.as_view(), name='edit-profile'),
 	path('settings/reg-face/', views.UserFaceRegView.as_view(), name='reg-face'),
 	path('apis/auth/', views.UserFaceLogInView.as_view(), name='api-auth')
]

recognition/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class FaceSignature(models.Model):
	user=models.OneToOneField(User, on_delete=models.CASCADE)
	signatures=models.TextField(null=True)
	face=models.TextField(null=True)
	def __str__(self):
		return self.user.username

@receiver(post_save, sender=User)
def create_user_face_signeture(sender, instance, created, **kwargs):
    if created:
        FaceSignature.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_face_signeture(sender, instance, **kwargs):
	if(instance.facesignature is None):
		FaceSignature.objects.create(user=instance)
	else:
		instance.facesignature.save()


class UserProfile(models.Model):
	user = models.OneToOneField(User, related_name='profile',on_delete=models.CASCADE)
	firstname=models.CharField(max_length=100, default='', blank=True)
	lastname=models.CharField(max_length=100, default='', blank=True)
	photo = models.ImageField(null=True, blank=True)
	website = models.URLField(default='', blank=True)
	bio = models.TextField(default='', blank=True)
	phone = models.CharField(max_length=20, blank=True, default='')
	city = models.CharField(max_length=100, default='', blank=True)
	country = models.CharField(max_length=100, default='', blank=True)
	organization = models.CharField(max_length=100, default='', blank=True)

	def __str__(self):
		return self.user.username


@receiver(post_save, sender=User)
def create_update_user_profile(sender, instance, created, **kwargs):
	if created:
		UserProfile.objects.create(user=instance)
	instance.profile.save()

recognition/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import FaceSignature, UserProfile

class UserRegForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ('username','email','password')

class UserEditForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('email',)

class UserLoginForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput)
	password.widget.attrs.update({'class': 'form-control'})
	class Meta:
		model = User
		fields = ('username','password')

class UserFaceRegForm(forms.ModelForm):
	class Meta:
		model = FaceSignature
		fields={}

class UserProfileForm(forms.ModelForm):
	"""docstring for UserProfileForm"""
	class Meta:
		model = UserProfile
		fields = ('firstname','lastname','website','bio','phone','photo','city','country','organization')
		

recognition/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View

from django.shortcuts import render, redirect
from rest_framework.views import APIView
from rest_framework.response import Response

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.utils.decorators import method_decorator
from django.contrib import messages


from .forms import UserLoginForm, UserRegForm, UserFaceRegForm, UserEditForm, UserProfileForm

from .utils import Base64ToNpImage, TensorflowBridge, Recognizer, DlibBridge

from django.http import JsonResponse


import pickle
# Create your views here.
@method_decorator(login_required, name='get')
class Home(View):
	def get(self,request):
		return render(request,'recognition/home.html')


class LogoutView(View):
	def get(self,request):
		logout(request)
		return redirect('recognition:home')



class UserLoginView(View):
	form_class=AuthenticationForm
	template_name='recognition/login.html'

	def get(self,request):
		form=self.form_class(None)
		messages.info(request, '')
		return render(request,self.template_name,{'form':form})

	def post(self,request):
		form=self.form_class(data=request.POST)

		if form.is_valid():
			# clean normalize data
			username=form.cleaned_data['username']
			password=form.cleaned_data['password']

			#return if credentials are correct

			user=authenticate(username=username,password=password)

			if user is not None:
				if user.is_active:
					login(request, user)
					#TODO Redirect to Face Registration pageß
					return redirect('recognition:home')
			else:
				messages.error(request,'Invalid Username/Password')
		else:
			messages.error(request,'error')
		return render(request,self.template_name,{'form':form})

class UserRegistrationView(View):
	form_class=UserRegForm
	template_name='recognition/register.html'

	def get(self,request):
		form=self.form_class(None)
		return render(request,self.template_name,{'form':form})

	def post(self,request):
		form= self.form_class(request.POST)

		if form.is_valid():
			user=form.save(commit=False)
			# clean normalize data
			username=form.cleaned_data['username']
			password=form.cleaned_data['password']
			user.set_password(password)
			user.save()

			#return if credentials are correct

			user=authenticate(username=username,password=password)

			if user is not None:
				if user.is_active:
					login(request, user)
					#TODO Redirect to Face Registration pageß
					return redirect('recognition:home')
		print('something is wrong')
		return render(request,self.template_name,{'form':form})


@method_decorator(login_required, name='get')
@method_decorator(login_required, name='post')
class UserFaceRegView(View):
	form_class=UserFaceRegForm
	template_name='recognition/settings/reg-face.html'
	base64ToNpImage= Base64ToNpImage()
	tfBridge=DlibBridge()
	recogzr=Recognizer()

	def get(self,request):
		form=self.form_class(None)
		messages.info(request, '')
		return render(request,self.template_name)

	def post(self,request):

		data = request.POST.getlist('imgs[]')
		images= self.base64ToNpImage.decodeArray(data)
		faces = self.tfBridge.imagesToFaces(images,(160,160))
		# return err if no face found
		if len(faces)==0:
			return JsonResponse({'status':'failed'}, status=201)
		else:
			ppFaces=self.tfBridge.preprocessFaces(faces)
			embedded=self.tfBridge.embeddFaces(ppFaces)
			request.user.facesignature.signatures=pickle.dumps(embedded)
			request.user.facesignature.face=data[0]
			request.user.save()
			self.recogzr.train(User.objects.all(),fn=128)
			return JsonResponse({'status':'success'}, status=201)

class UserFaceLogInView(APIView):
	base64ToNpImage= Base64ToNpImage()
	tfBridge=DlibBridge()
	recogzr=Recognizer()

	def post(self,request):
		data = request.POST.getlist('imgs[]')
		images= self.base64ToNpImage.decodeArray(data)
		faces = self.tfBridge.imagesToFaces(images,(160,160))
		# return err if no face found
		if len(faces)==0:
			return JsonResponse({'status':'failed', 'msg':'No face detected'}, status=201)
		else:
			ppFaces=self.tfBridge.preprocessFaces(faces)
			embedded=self.tfBridge.embeddFaces(ppFaces)
			print(type(embedded))
			userIds=self.recogzr.predict(embedded)
			if(len(userIds)==0):
				return JsonResponse({'status':'failed','msg':'User not recognized'}, status=201)
			try:
				user = User.objects.get(id=userIds[0])

				dist = self.recogzr.getDistance(embedded,user)
				print(dist);
				if(dist>0.4):
					return JsonResponse({'status':'failed','msg':'User not recognized'}, status=201)
				# login without password
				user.backend = 'django.contrib.auth.backends.ModelBackend'
				login(request, user)
				return JsonResponse({'status':'success'}, status=201)
			except  User.DoesNotExist:
			   	#handle the case when the user does not exist.
			   	return JsonResponse({'status':'failed', 'msg':'user does not exist'}, status=201)



@method_decorator(login_required, name='get')
@method_decorator(login_required, name='post')
class ProfileSettingsView(UpdateView):
	"""docstring for ProfileSettingsView"""
	form_class=UserFaceRegForm
	template_name='recognition/settings/profile.html'

	def get(self,request):
		user_form = UserEditForm(instance=request.user)
		profile_form = UserProfileForm(instance=request.user.profile)
		messages.info(request, '')
		return render(request, self.template_name, {
		'user_form': user_form,
		'profile_form': profile_form})

	def post(self,request):
		user_form = UserEditForm(request.POST or None, request.FILES or None, instance=request.user)
		profile_form = UserProfileForm(request.POST or None, request.FILES or None, instance=request.user.profile)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			messages.success(request, 'Your profile was successfully updated!')
			return redirect('recognition:edit-profile')
		else:
			messages.error(request,'Please correct the error below.')

		return render(request, self.template_name, {'user_form': user_form, 'profile_form': profile_form})
# login without password
# user.backend = 'django.contrib.auth.backends.ModelBackend'
# login(request, user)

recognition/templates/recognition/settings/profile.html
{% extends 'recognition/base.html' %}


{% block head %}
{% endblock %}


{% block title %}{% block pagetitle %}Settings{% endblock %}{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-8">
      <form action="{% url 'recognition:edit-profile' %}" method="post" enctype="multipart/form-data">
        <div class="card">
          <div class="card-header">
            <h5 class="title">Edit Profile</h5>
          </div>
          <div class="card-body">
            {% if messages %}
            <ul>
              {% for message in messages %}
                 <li>{{ message }}</li>
              {% endfor %}
            </ul>
            {% endif %}
            
            {% csrf_token %}
            {% load widget_tweaks %}

            {% for hidden_field in user_form.hidden_fields %}
                {{ hidden_field }}
            {% endfor %}

            {% for field in user_form.visible_fields %}
            <div class="row">
              <div class="col-sm-10 offset-sm-1" >
                <div class="form-group">
                  <div class="row">
                    <div class="col-sm-10 offset-sm-2 text-center pagination-centered" >
                      <span class="text-denger small">{{field.errors}}</span>
                    </div>
                    <label class="control-label col-sm-4">{{field.label_tag}}</label>
                    <div class="col-sm-8">{% render_field field class="form-control" %}</div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
            <br/>
            {% for hidden_field in profile_form.hidden_fields %}
                {{ hidden_field }}
            {% endfor %}
            {% for field in profile_form.visible_fields %}
            <div class="row">
              <div class="col-sm-10 offset-sm-1" >
                <div class="form-group">
                  <div class="row">
                    <div class="col-sm-10 offset-sm-2 text-center pagination-centered" >
                      <span class="text-denger small">{{field.errors}}</span>
                    </div>
                    <label class="control-label col-sm-4">{{field.label_tag}}</label>
                    <div class="col-sm-8" style="color: wheat;">{% render_field field class="form-control" %}</div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-fill btn-primary">Save</button>
          </div>
        </div>
      </form>
    </div>
    <div class="col-md-4">
      <div class="card  card-user">
        <div class="card-body ">
          <p class="card-text">
            <div class="author">
              <div class="block block-one"></div>
              <div class="block block-two"></div>
              <div class="block block-three"></div>
              <div class="block block-four"></div>
              <a href="#">
                {% if user.profile.photo %}
                <img class="avatar" src="{{ user.profile.photo.url }}" alt="...">
                {% else %}
                <img class="avatar" src="" alt="...">
                {% endif %}
                <h5 class="title">{{ user.profile.firstname }} {{ user.profile.lastname }}</h5>
              </a>
              <p class="description">
                {{ user.profile.organization}}
              </p>
            </div>
          </p>
          <p class="card-description">
            {{ user.profile.bio }}
          </p>
        </div>
        <div class="card-footer ">
          <div class="button-container">
            <button href="#" class="btn btn-icon btn-round btn-facebook">
              <i class="fab fa-facebook"></i>
            </button>
            <button href="#" class="btn btn-icon btn-round btn-twitter">
              <i class="fab fa-twitter"></i>
            </button>
            <button href="#" class="btn btn-icon btn-round btn-google">
              <i class="fab fa-google-plus"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

recognition/templates/recognition/settings/reg-face.html
{% extends 'recognition/base.html'%}
{% block head %}
<style type="text/css">
	#container {
	    margin: 0px auto;
	    width: 500px;
	    height: 375px;
	    border: 10px #333 solid;
	}
	.canvasFrame {
	    width: 80%;
	    max-height: 240px;
	    background-color: #666;
	    border: 10px #333 solid;
	}
	#videoElement{
		width: 100%;
		
	}
	.hidden{
		display: none;
	}
	#canvasOutput{
		margin: auto;
	}
	
</style>

{% endblock %}

{% block title %}{% block pagetitle %}Settings{% endblock %}{% endblock %}

{% block body %}
<div class="row">
	<div class="col-md-5">
		<div class="row">
			<div class="card">
			    <div class="card-header text-center" style="padding: 20px;">
					<h5 class="title">Register</h5>
					<div class="canvasFrame" style="width:100%; text-align: center; overflow: hidden;">
						<video autoplay="true" id="videoElement"></video>
						<canvas id="canvasOutput"></canvas>
					</div>
			    </div>
			    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
				    <div class="card-body" style="min-height: 100px;">
				    	<div class="row">
				    		<div class="col-md-10 offset-md-1" >
				    			<div style="margin: 0 auto; width: 100%; text-align: center;">
				    				<label style="font-size: 15px; font-weight: 600; color: white; font-family: monospace;" id="lblStatus"></label>
				    			</div>
				    			<div id="trainLoader" class="hidden" style="margin: 0 auto; width: 100%; text-align: center;">
				    				<div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
				    			</div>
				    			<div id="videoFrameContainer" style="margin:0 auto; width: 100%; text-align:center;"></div>
				    		</div>
				    	</div>
						{% include 'recognition/form-template.html' %}
				    </div>
				    <div class="card-footer col-md-10 offset-md-1">
				    	<div class="row">
				    		<div class="col-md-4" style="text-align: center;">
				    			<button id="btnTakeSnap" class="btn btn-fill btn-block btn-info" style="padding-left: 0px; padding-right: 0px; ">Capture</button>
				    		</div>
				    		<div class="col-md-4" style="text-align: center;">
				    			<button id="btnReset" class="btn btn-fill btn-block btn-danger" style="padding-left: 0px; padding-right: 0px; ">Reset</button>
				    		</div>
				    		<div class="col-md-4" style="text-align: center;">
				      			<button id="btnTrain" class="btn btn-fill btn-block btn-primary" style="padding-left: 0px; padding-right: 0px; ">Train</button>
				      		</div>
				    	</div>
				    </div>
			    </form>
			</div>
		</div>
	</div>
</div>
{% endblock %}


{% block footerScript %}
{% load staticfiles%}
<script type="text/javascript">
	var video = document.querySelector("#videoElement");
	if (navigator.mediaDevices.getUserMedia) {       
	    navigator.mediaDevices.getUserMedia({video: true})
	  .then(function(stream) {
	    video.srcObject = stream;
	  })
	  .catch(function(err0r) {
	    console.log("Something went wrong!");
	  });
	}
</script>
<script src="{% static 'recognition' %}/js/opencv.js" type="text/javascript"></script>
<script src="{% static 'recognition' %}/js/utils.js"  type="text/javascript"></script>
<script src="{% static 'recognition' %}/js/facedetect.js" onload="opencvIsReady()" type="text/javascript"></script>
<script>
	document.querySelector("#btnTakeSnap").addEventListener("click", function(event){
	    event.preventDefault()
	    captureFrame()
	});
	document.querySelector("#btnReset").addEventListener("click", function(event){
	    event.preventDefault();
	    var container = document.querySelector("#videoFrameContainer");
	    container.innerHTML = '';
	});
	document.querySelector("#btnTrain").addEventListener("click", function(event){
	    event.preventDefault();
	    register();
	});
	function captureFrame() {
		var container = document.querySelector("#videoFrameContainer");
		if (container.childElementCount>=5|| faceDetected==false) {
			return
		}


		var canvas = document.createElement('canvas');
		var video = document.querySelector("#videoElement");
		canvas.width = video.videoWidth;
		canvas.height = video.videoHeight;
		canvas.style.width=String(video.videoWidth/10)+"px";
		canvas.style.height=String(video.videoHeight/10)+"px";
		canvas.style.zIndex = 8;
		canvas.style.border = "1px solid";
		var ctx = canvas.getContext('2d');
        ctx.drawImage(video, 0, 0, video.videoWidth, video.videoHeight);
        container.appendChild(canvas);

	}

	function register(){
		var container = document.querySelector("#videoFrameContainer");
		var status = document.querySelector("#lblStatus");
		if (container.childElementCount<5) {
			status.innerHTML="Capture 5 samples first to train"
			return
		}
	
		var train = document.querySelector("#btnTrain")
		if (train.classList.contains("disabled")){return}
		train.classList.add("disabled")

		var loader = document.querySelector("#trainLoader");
		var canva = container.childNodes;
		var imgData=[]
		canva.forEach(function(canvas){
		    imgData.push(canvas.toDataURL());
		});
		container.classList.add("hidden");
		loader.classList.remove("hidden");
		status.innerHTML="Training"
		status.classList.add("glow");
		$.ajax({
		  type: "POST",
		  url: "{% url 'recognition:reg-face' %}",
		  data: {
		  	'imgs[]':imgData,
		  	csrfmiddlewaretoken: '{{ csrf_token }}'
		  }
		}).done(function(response) {
			console.log('saved'); 
			console.log(response);
			loader.classList.add("hidden");
			container.classList.remove("hidden");
			status.classList.remove("glow");
			train.classList.remove("disabled")
			status.innerHTML="Training complete"
			container.innerHTML = '';
		});
	}
</script>
{% endblock%}